name: BlueMapSkinsRestorerProvider
version: ${project.version}
main: org.aurorus.bluemapskinsrestorerprovider.Main
api-version: 1.13
depend:
  - BlueMap
  - SkinsRestorer
authors: [ Aurorus ]
description: ${project.description}
website: ${project.url}
