name: BlueMapSkinsRestorerProvider
version: ${project.version}
main: org.aurorus.bluemapskinsrestorerprovider
api-version: 1.13
load: POSTWORLD
depend:
  - BlueMap
  - SkinsRestorer
authors: [ TechnicJelle, Aurorus ]
description: ${project.description}
website: ${project.url}
